# Generated by Django 4.2.6 on 2023-10-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_faqs_usercases_workprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainpageHtmlContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='述而作', max_length=200)),
                ('top_0', models.CharField(default='述而作=倾听之耳+生花妙笔+无限可能', max_length=200)),
                ('top_1', models.CharField(default='您说我写，“述而作”可以帮您把聊天、谈话、会议、课程、口述其至呢喃快速转化为清晰可使用可发布的文字', max_length=200)),
                ('top_2', models.CharField(default='助力您极速撰写文章、邮件、博客、报告、作文、说明、议论等', max_length=200)),
                ('top_3', models.CharField(default='-', max_length=200)),
                ('top_4', models.CharField(default='-', max_length=200)),
                ('top_5', models.CharField(default='-', max_length=200)),
                ('mid_0', models.CharField(default='应用场景', max_length=200)),
                ('mid_1', models.CharField(default='常见问题', max_length=200)),
                ('mid_2', models.CharField(default='-', max_length=200)),
                ('mid_3', models.CharField(default='-', max_length=200)),
                ('mid_4', models.CharField(default='-', max_length=200)),
                ('mid_5', models.CharField(default='-', max_length=200)),
                ('bottom_0', models.CharField(default='易谙科技', max_length=200)),
                ('bottom_1', models.CharField(default='述而作', max_length=200)),
                ('bottom_2', models.CharField(default='faqs', max_length=200)),
                ('bottom_3', models.CharField(default='隐私策略', max_length=200)),
                ('bottom_4', models.CharField(default='工作流程', max_length=200)),
                ('bottom_5', models.CharField(default='-', max_length=200)),
                ('bottom_6', models.CharField(default='-', max_length=200)),
                ('bottom_7', models.CharField(default='-', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrimeHtmlContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('context', models.TextField(blank=True, default='', max_length=1000)),
                ('annalPrice', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
