# Generated by Django 4.2.6 on 2023-10-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mainpagehtmlcontent_primehtmlcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='primehtmlcontent',
            name='cssStyles',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='primehtmlcontent',
            name='imagesPath',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
