# Generated by Django 4.2.6 on 2023-10-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_styletypes_importstring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notesdata',
            name='originalNotes',
        ),
        migrations.RemoveField(
            model_name='notesdata',
            name='rewriteNotes',
        ),
        migrations.RemoveField(
            model_name='notesdata',
            name='transcriptNotes',
        ),
        migrations.AddField(
            model_name='notesdata',
            name='ori',
            field=models.TextField(default='defalute ori notes', max_length=100000),
        ),
        migrations.AddField(
            model_name='notesdata',
            name='title',
            field=models.CharField(default='title', max_length=1000),
        ),
        migrations.AddField(
            model_name='notesdata',
            name='trans_res',
            field=models.TextField(default='defalute transcript notes', max_length=100000),
        ),
    ]
