# Generated by Django 4.2.6 on 2023-11-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_notesdata_originalnotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesdata',
            name='tag_6',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
