# Generated by Django 4.2.6 on 2023-11-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_notesdata_tag_6'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesdata',
            name='file_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
