# Generated by Django 4.2.6 on 2023-10-26 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0002_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
