# Generated by Django 4.2.6 on 2023-10-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0003_uploadedfile_created_at_uploadedfile_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='media/audio_files/'),
        ),
    ]
