# Generated by Django 4.2.6 on 2023-11-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0005_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
